service: products-service

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-west-1
  apiGateway:
    minimumCompressionSize: 1024
    shouldStartNameWithService: true
  environment:
    PG_HOST: ${env:PG_HOST} 
    PG_PORT: ${env:PG_PORT} 
    PG_DATABASE: ${env:PG_DATABASE} 
    PG_USERNAME: ${env:PG_USERNAME} 
    PG_PASSWORD: ${env:PG_PASSWORD} 
  
plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-dotenv-plugin

# plugins and specific conditions 
useDotenv: true

functions:
  getProductList:
    handler: handlers.getProductsList
    events:
      - http:
          path: /products
          method: get
          cors: true
  getProductsById:
    handler: handlers.getProductsById
    events:
      - http:
          path: /products/{productId}
          method: get
          cors: true
  createProduct:
    handler: handlers.createProduct
    events:
      - http:
          path: /products
          method: post
          cors: true